# Dockerfile.worker
FROM python:3.11-slim

# Diretório de trabalho
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

ENV PYTHONPATH=/app/src

# Comando padrão para rodar o collector
CMD ["python", "src/worker/collector.py"]
